source 'https://rubygems.org'

gem 'activerecord'
gem 'pg'
gem 'elasticsearch'
gem 'aws-sdk', '~> 3'
gem 'faraday'
gem 'net-http-persistent'
gem 'sidekiq'
gem 'jemalloc', git: 'https://github.com/travis-ci/jemalloc-rb'
gem 'redis-namespace'
